-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 20:48:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SABER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SABER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SABER` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SABER` ;

-- -----------------------------------------------------
-- Table `SABER`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_Departamento1_idx` (`departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_Departamento1`
    FOREIGN KEY (`departamento`)
    REFERENCES `SABER`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SABER`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Departamento` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SABER`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Estudiante` (
  `codigo` INT(11) NOT NULL,
  `cohorte` INT(11) NULL DEFAULT NULL,
  `sem_actual` INT(11) NULL DEFAULT NULL,
  `estrato` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(8) NULL DEFAULT NULL,
  `promedio_acumulado` INT(11) NULL DEFAULT NULL,
  `reliq_casos_especiales` INT(11) NULL DEFAULT NULL,
  `ult_exos_aplicadas` VARCHAR(79) NULL DEFAULT NULL,
  `opcion_ingeso` VARCHAR(1) NULL DEFAULT NULL,
  `tipo_ingreso` VARCHAR(11) NULL DEFAULT NULL,
  `cupo_especial_ingreso` VARCHAR(7) NULL DEFAULT NULL,
  `ult_promedio_semestral` INT(11) NULL DEFAULT NULL,
  `porc_creditos_aprobados` INT(11) NULL DEFAULT NULL,
  `nombre_situacion` VARCHAR(22) NULL DEFAULT NULL,
  `numero_readmisiones` INT(11) NULL DEFAULT NULL,
  `numero_plan` INT(11) NULL DEFAULT NULL,
  `gano_examen_ingles` BIT(1) NULL DEFAULT NULL,
  `tipo_colegio` VARCHAR(7) NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NULL DEFAULT NULL,
  `colegio` VARCHAR(43) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `anyo_11` BIT(1) NULL DEFAULT NULL,
  `pago_sem_actual` VARCHAR(12) NULL DEFAULT NULL,
  `modalidad` VARCHAR(1) NULL DEFAULT NULL,
  `nivel_estudio` VARCHAR(2) NULL DEFAULT NULL,
  `mencion_honorofica` VARCHAR(7) NULL DEFAULT NULL,
  `fecha_grado` VARCHAR(10) NULL DEFAULT NULL,
  `saber11` VARCHAR(14) NULL DEFAULT NULL,
  `saberPro` VARCHAR(14) NULL DEFAULT NULL,
  `ult_periodo_academico` VARCHAR(6) NULL DEFAULT NULL,
  `ult_periodo_pagado` VARCHAR(6) NULL DEFAULT NULL,
  `ult_tipo_pago` VARCHAR(23) NULL DEFAULT NULL,
  `ult_valor_pagado` INT(11) NULL DEFAULT NULL,
  `ult_periodo_liquidado` VARCHAR(6) NULL DEFAULT NULL,
  `ult_valor_liquidado` INT(11) NULL DEFAULT NULL,
  `total_periodos_academicos` INT(11) NULL DEFAULT NULL,
  `total_periodos_pagados` INT(11) NULL DEFAULT NULL,
  `puntaje_admision` INT(11) NULL DEFAULT NULL,
  `condigo_joven_en_accion` VARCHAR(1) NULL DEFAULT NULL,
  `num_registro` VARCHAR(14) NULL DEFAULT NULL,
  `grupo_ref` VARCHAR(23) NULL DEFAULT NULL,
  `puntaje_global` INT(11) NULL DEFAULT NULL,
  `percentil_nal_global` INT(11) NULL DEFAULT NULL,
  `percentil_grupo_ref` INT(11) NULL DEFAULT NULL,
  `nivel_desemp_competencias_ciudadanas` INT(11) NULL DEFAULT NULL,
  `nivel_desemp_comunicacion_escrita` INT(11) NULL DEFAULT NULL,
  `nivel_desemp_ingles` VARCHAR(3) NULL DEFAULT NULL,
  `nivel_desemp_lectura_critica` INT(11) NULL DEFAULT NULL,
  `nivel_desemp_razonamiento_cuantitativo` INT(11) NULL DEFAULT NULL,
  `percentil_grupo_ref_mod_competencias_ciudadanas` INT(11) NULL DEFAULT NULL,
  `percentil_grupo_ref_mod_comunicacion_escrita` INT(11) NULL DEFAULT NULL,
  `percentil_grupo_ref_mod_ingles` INT(11) NULL DEFAULT NULL,
  `percentil_grupo_ref_mod_lectura_critica` INT(11) NULL DEFAULT NULL,
  `percentil_grupo_ref_mod_razonamiento_cuantitativo` INT(11) NULL DEFAULT NULL,
  `percentil_nal_mod_competencias_ciudadanas` INT(11) NULL DEFAULT NULL,
  `percentil_nal_mod_comunicacion_escrita` INT(11) NULL DEFAULT NULL,
  `percentil_nal_mod_ingles` INT(11) NULL DEFAULT NULL,
  `percentil_nal_mod_lectura_critica` INT(11) NULL DEFAULT NULL,
  `percentil_nal_mod_razonamiento_cuantitativo` INT(11) NULL DEFAULT NULL,
  `puntaje_mod_competencias_ciudadanas` INT(11) NULL DEFAULT NULL,
  `puntaje_mod_comunicacion_escrita` INT(11) NULL DEFAULT NULL,
  `puntaje_mod_ingles` INT(11) NULL DEFAULT NULL,
  `puntaje_mod_lectura_critica` INT(11) NULL DEFAULT NULL,
  `puntaje_mod_razonamiento_cuantitativo` INT(11) NULL DEFAULT NULL,
  `periodo_exam` VARCHAR(6) NULL DEFAULT NULL,
  `prom_acum_exam` INT(11) NULL DEFAULT NULL,
  `Programa_codigo` INT NOT NULL,
  `ciudad_origen` INT NOT NULL,
  `ciudad_recidencia` INT NOT NULL,
  `ciudad_colegio` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_SaberPro_Programa1_idx` (`Programa_codigo` ASC) VISIBLE,
  INDEX `fk_SaberPro_Ciudad1_idx` (`ciudad_origen` ASC) VISIBLE,
  INDEX `fk_SaberPro_Ciudad2_idx` (`ciudad_recidencia` ASC) VISIBLE,
  INDEX `fk_SaberPro_Ciudad3_idx` (`ciudad_colegio` ASC) VISIBLE,
  CONSTRAINT `fk_SaberPro_Programa1`
    FOREIGN KEY (`Programa_codigo`)
    REFERENCES `SABER`.`Programa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaberPro_Ciudad1`
    FOREIGN KEY (`ciudad_origen`)
    REFERENCES `SABER`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaberPro_Ciudad2`
    FOREIGN KEY (`ciudad_recidencia`)
    REFERENCES `SABER`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaberPro_Ciudad3`
    FOREIGN KEY (`ciudad_colegio`)
    REFERENCES `SABER`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SABER`.`Estudiante_has_Exoneraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Estudiante_has_Exoneraciones` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Estudiante_has_Exoneraciones` (
  `Estudiante_codigo` INT(11) NOT NULL,
  `Exoneraciones_id` INT NOT NULL,
  PRIMARY KEY (`Estudiante_codigo`, `Exoneraciones_id`),
  INDEX `fk_Estudiante_has_Exoneraciones_Exoneraciones1_idx` (`Exoneraciones_id` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Exoneraciones_Estudiante1_idx` (`Estudiante_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Exoneraciones_Estudiante1`
    FOREIGN KEY (`Estudiante_codigo`)
    REFERENCES `SABER`.`Estudiante` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Exoneraciones_Exoneraciones1`
    FOREIGN KEY (`Exoneraciones_id`)
    REFERENCES `SABER`.`Exoneraciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SABER`.`Estudiante_has_Readmision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Estudiante_has_Readmision` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Estudiante_has_Readmision` (
  `Estudiante_codigo` INT(11) NOT NULL,
  `Periodo_id` INT NOT NULL,
  PRIMARY KEY (`Estudiante_codigo`, `Periodo_id`),
  INDEX `fk_Estudiante_has_Periodo_Periodo1_idx` (`Periodo_id` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Periodo_Estudiante1_idx` (`Estudiante_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Periodo_Estudiante1`
    FOREIGN KEY (`Estudiante_codigo`)
    REFERENCES `SABER`.`Estudiante` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Periodo_Periodo1`
    FOREIGN KEY (`Periodo_id`)
    REFERENCES `SABER`.`Periodo` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SABER`.`Exoneraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Exoneraciones` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Exoneraciones` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SABER`.`Facultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Facultad` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Facultad` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SABER`.`Periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Periodo` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Periodo` (
  `idtable1` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SABER`.`Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABER`.`Programa` ;

CREATE TABLE IF NOT EXISTS `SABER`.`Programa` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `facultad_codigo` INT NOT NULL,
  `snies_prg` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Programa_facultad_idx` (`facultad_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Programa_facultad`
    FOREIGN KEY (`facultad_codigo`)
    REFERENCES `SABER`.`Facultad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
