# Generated by Django 3.1.11 on 2021-06-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('new_file', models.FileField(blank=True, null=True, upload_to='data/archivos/')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
    ]
