# Generated by Django 3.1.7 on 2021-03-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0002_entrada_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
