# Generated by Django 3.1.7 on 2021-03-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0003_auto_20210328_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='fecha_creacion',
        ),
    ]
