# Generated by Django 3.1.7 on 2021-03-31 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talento', '0006_entrada_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='user',
        ),
        migrations.AddField(
            model_name='entrada',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
