# Generated by Django 3.1.7 on 2021-03-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0007_auto_20210330_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='created',
        ),
    ]
